### ISSUE TITLE
Mac java

### ISSUE THREAD

**Issue by alchemyst** [undeadpebble/UP-Class-Admin#1]
Stuff works a bit differently on the Mac than on Windows - [here are some tips](https://developer.apple.com/library/mac/#documentation/Java/Conceptual/Java14Development/07-NativePlatformIntegration/NativePlatformIntegration.html#//apple_ref/doc/uid/TP40001909-SW1) on how to get good native-looking apps

**Comment by claravanstaden** [comment]
Thanks, will have a look.
------Original Message------
From: Carl Sandrock
To: Clar64
Subject: [UP-Class-Admin] Mac java (#1)
Sent: Aug 1, 2012 14:39

Stuff works a bit differently on the Mac than on Windows - [here are some tips](https://developer.apple.com/library/mac/#documentation/Java/Conceptual/Java14Development/07-NativePlatformIntegration/NativePlatformIntegration.html#//apple_ref/doc/uid/TP40001909-SW1) on how to get good native-looking apps

---

Reply to this email directly or view it on GitHub:
https://github.com/undeadpebble/UP-Class-Admin/issues/1

Sent via my BlackBerry from Vodacom - let your email find you!

**Comment by claravanstaden** [comment]
Gee die GUI probleme op Mac?

**Comment by alchemyst** [comment]
Biggest issue is that the menu is attached to the window rather than the top of the screen, as is customary in the Mac. More info: http://www.milesdennis.com/2010/05/mac-menus-for-java-applications.html

**Comment by alchemyst** [comment]
I'm guessing the second issue is related to the first: the icons at the bottom are halfway off the screen. I believe this is because the initial window size is underestimated due to the extra size of the menu. The icons reposition correctly when the window is resized. I will add this as a seperate issue.

**Comment by claravanstaden** [comment]
Thanks, I will look at it.

**Comment by claravanstaden** [comment]
All issues is fixed. Bottom navigation bar is showing and menu bar is on top of screen, not attached to app window. See clara branch. Will merge to dev soon.
