### ISSUE TITLE
Filter based on values

### ISSUE THREAD

**Issue by alchemyst** [undeadpebble/UP-Class-Admin#17]
Something like the "autofilter" option in Excel, which allows one to select rows to display based on matching a particular column.

**Comment by wendersnawen** [comment]
Is this not basically what the conditional formatting does ? If not can you please tell me what the difference is.

**Comment by alchemyst** [comment]
I'm talking about something like this: http://www.contextures.com/xlautofilter01.html

**Comment by wendersnawen** [comment]
Do you want the option to remove all the rows that are not formatted by a conditional formatting? Or do you want to have another option apart from the conditional formatting which will only show the rows not formatted ?

**Comment by alchemyst** [comment]
I see filtering as completely separate from conditional formatting. The one has to do with visibility of particular rows based on values. The other has to do with their appearance. If the table were a database table, filtering is essentially a simple front-end for a select statement. Imagine the class list had a "gender" column. Filtering would allow me to see only the males or only the females. The problem with conditional formatting is that there may be relatively few values highlighted, so hiding the other rows will make it a lot easier.

Also, remember that some of the columns may be the result of the application of some kind of rule. I would imagine the better design here would be to start with the idea of a rule-calculated column, and simplify the conditional formatting to simply applying formatting based on the value of a column.
