### ISSUE TITLE
Column data types and validation

### ISSUE THREAD

**Issue by alchemyst** [undeadpebble/UP-Class-Admin#18]
Columns should be typed (string/integer/float/etc), with validation of values. It should be impossible to enter values outside of the range that is defined for the numeric columns.

**Comment by wendersnawen** [comment]
Currently if you type in a invalid value into a double field, it is not saved until it is validated, when you have finished editing, eg. clicked on another cell in the table, or pressed enter, the table checks if the value in the changed cell is valid. Is that what you mean ?

**Comment by alchemyst** [comment]
I know the validation logic is there, but there should be a way to set the valid values per column. For instance for a particular test that counts out of 10 only values between 0 and 10 should be accepted. At the moment I can enter -1 in the numeric columns and it is accepted.
