### ISSUE TITLE
Heavy CPU usage on window drawing

### ISSUE THREAD

**Issue by alchemyst** [undeadpebble/UP-Class-Admin#19]
The application is using pretty huge amounts of CPU for drawing itself. Profiling reveals that the following methods are being called continuously: 

ClassAdminFrontEnd.BackgroundGradientPanel.paintComponent(java.awt.Graphics)
ClassAdminFrontEnd.ReflectionButton.paintComponent(java.awt.Graphics)
ClassAdminFrontEnd.ThreeStopGradientPanel.paintComponent(java.awt.Graphics) 
ClassAdminFrontEnd.ImagePanel.paintComponent(java.awt.Graphics)
ClassAdminFrontEnd.ShadowPanel.paintComponent(java.awt.Graphics)
ClassAdminFrontEnd.FadePanel.paintComponent(java.awt.Graphics)

I recommend running Java VisualVM to track this issue down, I don't think the app should be redrawing this much.

**Comment by claravanstaden** [comment]
Improvements made, no longer draws when unnecessary.
