### ISSUE TITLE
Copy successful UI from Excel for conditional formatting

### ISSUE THREAD

**Issue by alchemyst** [undeadpebble/UP-Class-Admin#24]
http://www.homeandlearn.co.uk/excel2007/excel2007s6p2.html

**Comment by wendersnawen** [comment]
What part of that do you want implemented, the gradients in the color, or the list of all the conditional formatting ?

**Comment by alchemyst** [comment]
I would like colour scales, but I was actually talking about the layout of the current conditional formatting form - it is awkward. I think at least you should use a colour picker, but also the "add format" button is in the wrong place (should be at the bottom somewhere).

**Comment by wendersnawen** [comment]
The current layout is just for testing purposes and will be eddited to a better layout once the functionality is complete. And ok a colour picker will be added

**Comment by alchemyst** [comment]
You will notice that this is labelled as an enhancement rather than a bug. These issues are meant to keep a list of wanted items.

**Comment by wendersnawen** [comment]
Ah ok, makes sense
